### PR TITLE
NS 7 support

### PR DESCRIPTION
**Pull request by wendt88**
https://github.com/EddyVerbruggen/nativescript-calendar/issues/60

### CODE REVIEW

**Comment by wendt88** [comment]
@cla-bot check

**Comment by wendt88** [comment]
[clabot:check]

**Comment by choang10** [comment]
@EddyVerbruggen any idea when this will be looked at / merged? We're using a local copy of @wendt88's fork but would prefer to use yours if you intend to continue maintaining it. Thanks in advance (and thanks to @wendt88 for the PR!)

**Comment by EddyVerbruggen** [comment]
Excellent work, thanks!

**Pull request merged**
